
ZIP= jquery-3.4.1.min.js v.js v2sdl.js index.html projector.svg style.css group_000/Color_Bars_1920x1080.png group_000/Grid_Test_1920x1080.png

static.s: ../mkstatic/mkstatic.go ${ZIP}
	go run ../mkstatic/mkstatic.go ${ZIP} > static.s

